package com.vistas;

/**
 * @version 1.0
 * @author Edgar Retana
 */
public class FormSolicitudSSE extends javax.swing.JInternalFrame {

    
    
    public FormSolicitudSSE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        spin_fecha_solicitud = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        combo_sede_itca = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        txt_carnet = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        combo_escuela = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        combo_carrera = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        txt_institucion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_destinatario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_comentarios = new javax.swing.JTextArea();
        btn_limpiar = new javax.swing.JButton();
        btn_enviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Solicitud de Servicio Social");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Fecha de Solicitud:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        spin_fecha_solicitud.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        getContentPane().add(spin_fecha_solicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, -1));

        jLabel3.setText("Nombres:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        getContentPane().add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, -1));

        jLabel4.setText("Apellidos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));
        getContentPane().add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 230, -1));

        jLabel5.setText("Sede ITCA FEPADE:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        getContentPane().add(combo_sede_itca, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 230, -1));

        jLabel6.setText("Carnet:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        getContentPane().add(txt_carnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, -1));

        jLabel7.setText("Escuela:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        getContentPane().add(combo_escuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 200, -1));

        jLabel8.setText("Carrera:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        getContentPane().add(combo_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 230, -1));

        jLabel9.setText("Institución donde se realizará el SSE:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        getContentPane().add(txt_institucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, -1));

        jLabel10.setText("Destinatario de la solicitud:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));
        getContentPane().add(txt_destinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 230, -1));

        jLabel11.setText("Comentarios acerca de la solicitud:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        txt_comentarios.setColumns(20);
        txt_comentarios.setRows(5);
        jScrollPane1.setViewportView(txt_comentarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 480, 100));

        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/clean.png"))); // NOI18N
        btn_limpiar.setText("Limpiar Formulario");
        btn_limpiar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        btn_enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/send.png"))); // NOI18N
        btn_enviar.setText("Enviar Solicitud");
        btn_enviar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btn_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/bg7.jpg"))); // NOI18N
        jLabel1.setText("Carnet:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JComboBox<String> combo_carrera;
    private javax.swing.JComboBox<String> combo_escuela;
    private javax.swing.JComboBox<String> combo_sede_itca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spin_fecha_solicitud;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_carnet;
    private javax.swing.JTextArea txt_comentarios;
    private javax.swing.JTextField txt_destinatario;
    private javax.swing.JTextField txt_institucion;
    private javax.swing.JTextField txt_nombres;
    // End of variables declaration//GEN-END:variables
}
