/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vistas;

import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author edgar
 */
public class FormEstadoSolicitudSSE extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormEstadoSolicitudSSE
     */
    public FormEstadoSolicitudSSE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_nueva_solicitud = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Estado de Solicitud de SSE");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/graduation.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_nueva_solicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/new_doc.png"))); // NOI18N
        btn_nueva_solicitud.setText("Nueva Solicitud SSE");
        btn_nueva_solicitud.setIconTextGap(8);
        btn_nueva_solicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nueva_solicitudMouseClicked(evt);
            }
        });
        getContentPane().add(btn_nueva_solicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Institucion de SSE", "Estado", "Accion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 490, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/bg7.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nueva_solicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nueva_solicitudMouseClicked
        JDesktopPane desktop = (JDesktopPane) this.getParent();
        int deskHeight = desktop.getSize().height;
        int deskWidth = desktop.getSize().width;
        
        FormSolicitudSSE form = new FormSolicitudSSE();
        desktop.add(form);
        
        form.setMaximizable(false);
        form.show();
        form.setLocation((deskWidth - form.getWidth())/2, (deskHeight - form.getHeight())/2);
        this.dispose();
        desktop.repaint();
    }//GEN-LAST:event_btn_nueva_solicitudMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_nueva_solicitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
