/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vistas;

/**
 *
 * @author edgar
 */
public class PanelEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form PanelCoordinador
     */
    public PanelEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_solicitudsse = new javax.swing.JLabel();
        btn_horariosse = new javax.swing.JLabel();
        btn_controlsse = new javax.swing.JLabel();
        btn_finalizacionsse = new javax.swing.JLabel();
        btn_notas = new javax.swing.JLabel();
        btn_notas1 = new javax.swing.JLabel();

        btn_solicitudsse.setBackground(new java.awt.Color(48, 80, 101));
        btn_solicitudsse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_solicitudsse.setForeground(new java.awt.Color(255, 255, 255));
        btn_solicitudsse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_solicitudsse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/survey.png"))); // NOI18N
        btn_solicitudsse.setText("Solicitud SSE");
        btn_solicitudsse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btn_solicitudsse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_solicitudsse.setIconTextGap(10);
        btn_solicitudsse.setName("solicitud_sse"); // NOI18N
        btn_solicitudsse.setOpaque(true);

        btn_horariosse.setBackground(new java.awt.Color(48, 80, 101));
        btn_horariosse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_horariosse.setForeground(new java.awt.Color(255, 255, 255));
        btn_horariosse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_horariosse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/clock.png"))); // NOI18N
        btn_horariosse.setText("Horario SSE");
        btn_horariosse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btn_horariosse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_horariosse.setIconTextGap(10);
        btn_horariosse.setName("horario_sse"); // NOI18N
        btn_horariosse.setOpaque(true);

        btn_controlsse.setBackground(new java.awt.Color(48, 80, 101));
        btn_controlsse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_controlsse.setForeground(new java.awt.Color(255, 255, 255));
        btn_controlsse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_controlsse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/calendar.png"))); // NOI18N
        btn_controlsse.setText("Control SSE");
        btn_controlsse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btn_controlsse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_controlsse.setIconTextGap(10);
        btn_controlsse.setName("control_sse"); // NOI18N
        btn_controlsse.setOpaque(true);

        btn_finalizacionsse.setBackground(new java.awt.Color(48, 80, 101));
        btn_finalizacionsse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_finalizacionsse.setForeground(new java.awt.Color(255, 255, 255));
        btn_finalizacionsse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_finalizacionsse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/finish.png"))); // NOI18N
        btn_finalizacionsse.setText("Finalizacion SSE");
        btn_finalizacionsse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btn_finalizacionsse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_finalizacionsse.setIconTextGap(10);
        btn_finalizacionsse.setName("finalizacion_sse"); // NOI18N
        btn_finalizacionsse.setOpaque(true);

        btn_notas.setBackground(new java.awt.Color(48, 80, 101));
        btn_notas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_notas.setForeground(new java.awt.Color(255, 255, 255));
        btn_notas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_notas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/anote.png"))); // NOI18N
        btn_notas.setText("Mis Notas");
        btn_notas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btn_notas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_notas.setIconTextGap(10);
        btn_notas.setName("notas_ciclo"); // NOI18N
        btn_notas.setOpaque(true);

        btn_notas1.setBackground(new java.awt.Color(48, 80, 101));
        btn_notas1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_notas1.setForeground(new java.awt.Color(255, 255, 255));
        btn_notas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_notas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/help.png"))); // NOI18N
        btn_notas1.setText("Horarios Consulta");
        btn_notas1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btn_notas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_notas1.setIconTextGap(10);
        btn_notas1.setName("horarios_consulta"); // NOI18N
        btn_notas1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_controlsse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_finalizacionsse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btn_notas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_horariosse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_solicitudsse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_notas1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_solicitudsse, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_horariosse, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_controlsse, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_finalizacionsse, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_notas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_notas1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_controlsse;
    private javax.swing.JLabel btn_finalizacionsse;
    private javax.swing.JLabel btn_horariosse;
    private javax.swing.JLabel btn_notas;
    private javax.swing.JLabel btn_notas1;
    private javax.swing.JLabel btn_solicitudsse;
    // End of variables declaration//GEN-END:variables
}
