/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vistas;

/**
 *
 * @author edgar
 */
public class PanelAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        btn_horariocoor = new javax.swing.JLabel();
        btn_horariocoor1 = new javax.swing.JLabel();
        btn_horariocoor2 = new javax.swing.JLabel();
        btn_horariocoor3 = new javax.swing.JLabel();
        btn_horariocoor4 = new javax.swing.JLabel();

        btn_horariocoor.setBackground(new java.awt.Color(48, 80, 101));
        btn_horariocoor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_horariocoor.setForeground(new java.awt.Color(255, 255, 255));
        btn_horariocoor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_horariocoor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/build.png"))); // NOI18N
        btn_horariocoor.setText("Sedes");
        btn_horariocoor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btn_horariocoor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_horariocoor.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_horariocoor.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_horariocoor.setName("sede_itca"); // NOI18N
        btn_horariocoor.setOpaque(true);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btn_horariocoor, org.jdesktop.beansbinding.ELProperty.create("60"), btn_horariocoor, org.jdesktop.beansbinding.BeanProperty.create("iconTextGap"));
        bindingGroup.addBinding(binding);

        btn_horariocoor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_horariocoorMouseClicked(evt);
            }
        });

        btn_horariocoor1.setBackground(new java.awt.Color(48, 80, 101));
        btn_horariocoor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_horariocoor1.setForeground(new java.awt.Color(255, 255, 255));
        btn_horariocoor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_horariocoor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/book.png"))); // NOI18N
        btn_horariocoor1.setText("Escuelas");
        btn_horariocoor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btn_horariocoor1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_horariocoor1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_horariocoor1.setName("escuelas"); // NOI18N
        btn_horariocoor1.setOpaque(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btn_horariocoor2, org.jdesktop.beansbinding.ELProperty.create("45"), btn_horariocoor1, org.jdesktop.beansbinding.BeanProperty.create("iconTextGap"));
        bindingGroup.addBinding(binding);

        btn_horariocoor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_horariocoor1MouseClicked(evt);
            }
        });

        btn_horariocoor2.setBackground(new java.awt.Color(48, 80, 101));
        btn_horariocoor2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_horariocoor2.setForeground(new java.awt.Color(255, 255, 255));
        btn_horariocoor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_horariocoor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/materials.png"))); // NOI18N
        btn_horariocoor2.setText("Carreras");
        btn_horariocoor2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btn_horariocoor2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_horariocoor2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_horariocoor2.setName("carreras"); // NOI18N
        btn_horariocoor2.setOpaque(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btn_horariocoor3, org.jdesktop.beansbinding.ELProperty.create("45"), btn_horariocoor2, org.jdesktop.beansbinding.BeanProperty.create("iconTextGap"));
        bindingGroup.addBinding(binding);

        btn_horariocoor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_horariocoor2MouseClicked(evt);
            }
        });

        btn_horariocoor3.setBackground(new java.awt.Color(48, 80, 101));
        btn_horariocoor3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_horariocoor3.setForeground(new java.awt.Color(255, 255, 255));
        btn_horariocoor3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_horariocoor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/abc.png"))); // NOI18N
        btn_horariocoor3.setText("Tipo de Carreras");
        btn_horariocoor3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btn_horariocoor3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_horariocoor3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_horariocoor3.setIconTextGap(5);
        btn_horariocoor3.setName("tipos_carreras"); // NOI18N
        btn_horariocoor3.setOpaque(true);
        btn_horariocoor3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_horariocoor3MouseClicked(evt);
            }
        });

        btn_horariocoor4.setBackground(new java.awt.Color(48, 80, 101));
        btn_horariocoor4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_horariocoor4.setForeground(new java.awt.Color(255, 255, 255));
        btn_horariocoor4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_horariocoor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/users.png"))); // NOI18N
        btn_horariocoor4.setText("Usuarios");
        btn_horariocoor4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btn_horariocoor4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_horariocoor4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_horariocoor4.setName("tipos_carreras"); // NOI18N
        btn_horariocoor4.setOpaque(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btn_horariocoor4, org.jdesktop.beansbinding.ELProperty.create("40"), btn_horariocoor4, org.jdesktop.beansbinding.BeanProperty.create("iconTextGap"));
        bindingGroup.addBinding(binding);

        btn_horariocoor4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_horariocoor4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_horariocoor, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btn_horariocoor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_horariocoor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_horariocoor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_horariocoor4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_horariocoor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_horariocoor1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_horariocoor2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_horariocoor3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_horariocoor4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        btn_horariocoor1.getAccessibleContext().setAccessibleName("escuelas");

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_horariocoorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_horariocoorMouseClicked

    }//GEN-LAST:event_btn_horariocoorMouseClicked

    private void btn_horariocoor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_horariocoor1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_horariocoor1MouseClicked

    private void btn_horariocoor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_horariocoor2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_horariocoor2MouseClicked

    private void btn_horariocoor3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_horariocoor3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_horariocoor3MouseClicked

    private void btn_horariocoor4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_horariocoor4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_horariocoor4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_horariocoor;
    private javax.swing.JLabel btn_horariocoor1;
    private javax.swing.JLabel btn_horariocoor2;
    private javax.swing.JLabel btn_horariocoor3;
    private javax.swing.JLabel btn_horariocoor4;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
